"""solving bug users

Revision ID: 160d433e112e
Revises: 9dbbb3fc4dfc
Create Date: 2024-08-07 23:59:39.191798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '160d433e112e'
down_revision: Union[str, None] = '9dbbb3fc4dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('maiden_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('status_user', sa.Integer(), nullable=False),
    sa.Column('fk_role_id', sa.Integer(), nullable=True),
    sa.Column('fk_users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_role_id'], ['role.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fk_users_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_fk_role_id'), 'users', ['fk_role_id'], unique=False)
    op.create_index(op.f('ix_users_fk_users_id'), 'users', ['fk_users_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_fk_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_fk_role_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
