"""First

Revision ID: 9dbbb3fc4dfc
Revises: 
Create Date: 2024-08-07 23:51:40.641358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dbbb3fc4dfc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requesttracing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_time', sa.String(), nullable=True),
    sa.Column('client_ip', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('status_code', sa.String(), nullable=True),
    sa.Column('response_time', sa.String(), nullable=True),
    sa.Column('request_body', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requesttracing_client_ip'), 'requesttracing', ['client_ip'], unique=False)
    op.create_index(op.f('ix_requesttracing_id'), 'requesttracing', ['id'], unique=False)
    op.create_index(op.f('ix_requesttracing_method'), 'requesttracing', ['method'], unique=False)
    op.create_index(op.f('ix_requesttracing_request_body'), 'requesttracing', ['request_body'], unique=False)
    op.create_index(op.f('ix_requesttracing_request_time'), 'requesttracing', ['request_time'], unique=False)
    op.create_index(op.f('ix_requesttracing_response'), 'requesttracing', ['response'], unique=False)
    op.create_index(op.f('ix_requesttracing_response_time'), 'requesttracing', ['response_time'], unique=False)
    op.create_index(op.f('ix_requesttracing_status_code'), 'requesttracing', ['status_code'], unique=False)
    op.create_index(op.f('ix_requesttracing_url'), 'requesttracing', ['url'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_requesttracing_url'), table_name='requesttracing')
    op.drop_index(op.f('ix_requesttracing_status_code'), table_name='requesttracing')
    op.drop_index(op.f('ix_requesttracing_response_time'), table_name='requesttracing')
    op.drop_index(op.f('ix_requesttracing_response'), table_name='requesttracing')
    op.drop_index(op.f('ix_requesttracing_request_time'), table_name='requesttracing')
    op.drop_index(op.f('ix_requesttracing_request_body'), table_name='requesttracing')
    op.drop_index(op.f('ix_requesttracing_method'), table_name='requesttracing')
    op.drop_index(op.f('ix_requesttracing_id'), table_name='requesttracing')
    op.drop_index(op.f('ix_requesttracing_client_ip'), table_name='requesttracing')
    op.drop_table('requesttracing')
    # ### end Alembic commands ###
